name: RocketPlaceholders
author: Lorenzo0111
main: me.lorenzo0111.rocketplaceholders.RocketPlaceholders
version: 1.7
softdepend: [PlaceholderAPI]
description: Create custom placeholders with PlaceholderAPI
commands:
  rocketplaceholders:
    description: RocketPlaceholders main command!
    aliases: [rp, placeholders]
permissions:
  rocketplaceholders.command:
    description: Placeholders command