name: "Build"

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
  javadocs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Generate Javadocs with Gradle
        run: ./gradlew javadoc

      - name: Deploy Javadocs
        if: ${{ github.event_name == 'push' && github.repository == 'Lorenzo0111/RocketPlaceholders' }}
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build/docs/javadoc --prod --message="GitHubActionsDeploy"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}