name: "Build"

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
  javadocs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Generate Javadocs with Gradle
        run: ./gradlew javadoc

      - name: Archive plugin jars on GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Plugin
          path: build/libs
